name: Azure Subscription Creation
on:
  push:
    branches:
      - master
    paths:
      - 'azure/*'
jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Placeholder
        run: echo 'Will be Azure sub creation'